{% set name = "injective-py" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/InjectiveLabs/sdk-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 829489369d66618fb1a190111b92f52e0de58d74c10efb312621d21b67af6fa0
  patches:
    - fix-protobuf-test-fail.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  host:
    - python >=3.9.0
    - coincurve
    - pip
    - poetry
  run:
    - aiocron
    - aiohttp
    - bech32
    - bip32
    - coincurve
    - ecdsa
    - eip712
    - grpcio
    - grpcio-tools
    - hdwallets
    - mnemonic
    - protobuf
    - python >=3.9.0
    - requests
    - safe-pysha3
    - urllib3 >=1.26.18,<2
    - websockets
    - web3 >=6

test:
  imports:
    - pyinjective
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-grpc
    - requests-mock
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/InjectiveLabs/sdk-python
  summary: 'Injective Python SDK, with Exchange API client'
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - NOTICE.md

extra:
  recipe-maintainers:
    - MementoRC
