{% set name = "injective-py" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/InjectiveLabs/sdk-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c7cbb5601f1508f6fd0a95c2cc0d7f32c09ed5490cbbb59a68ba84cdd59f17f6
  patches:
    - fix-protobuf-test-fail.patch
    - clean-lib-dependencies.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  number: 1

requirements:
  host:
    - aiohttp
    - python >=3.9.0
    - pip
    - poetry
  run:
    - bech32
    - bip32
    - ecdsa
    - eip712
    - grpcio
    - mnemonic
    - python >=3.9.0
    - requests
    - safe-pysha3
    - web3 >=6

test:
  imports:
    - pyinjective
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-grpc
    - requests-mock
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/InjectiveLabs/sdk-python
  summary: 'Injective Python SDK, with Exchange API client'
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - NOTICE.md

extra:
  recipe-maintainers:
    - MementoRC
