{% set name = "injective-py" %}
{% set version = "1.9.1" %}

# {% set python_min = "3.10" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/InjectiveLabs/sdk-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0f0add094fc0d2973dc8038677b5c041ef6466d296d40d645a55b1dd756c18d9
  patches:
    - patches/fix-protobuf-test-fail.patch
    - patches/clean-lib-dependencies.patch

build:
  # noarch: python
  skip: true  # [py < 39]
  script: {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  host:
    - aiohttp >=3.9.4
    - pip
    - poetry-core
    - python
  run:
    - bech32
    - bip32
    - ckzg <2  # [py < 313]
    - ckzg  # [py >= 313]
    - ecdsa
    - eip712
    - eth-abi
    - grpcio
    - mnemonic
    - python
    - requests
    - safe-pysha3
    - web3 >=6.0.0,<7.0.0  # [py < 313]
    - web3 >=7.0.0,<7.6.0  # [py >= 313]

test:
  imports:
    - pyinjective
  source_files:
    - tests
    - examples
    - pyproject.toml
  requires:
    - pip
    - poetry
    - pytest
    - pytest-asyncio
    - pytest-grpc
    - python
    - requests-mock
  commands:
    - pip check
    # Documented (incorrectly) examples do not work
    # - poetry run python examples/exchange_client/spot_exchange_rpc/8_StreamOrderbookUpdate.py
    # - poetry run python examples/chain_client/3_MessageBroadcaster.py

    # All tests are failing
    # - poetry run pytest -v

about:
  home: https://github.com/InjectiveLabs/sdk-python
  summary: 'Injective Python SDK, with Exchange API client'
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - NOTICE.md

extra:
  recipe-maintainers:
    - MementoRC
